### ISSUE TITLE
Issue to trigger new releases

### ISSUE THREAD

**Issue by pazzo83** [JuliaAI/MLJText.jl#14]
@JuliaRegistrator register branch=master

release notes:
- add `BM25Transformer` using the Okapi BM25 document-word statistic to represent a corpus of documents
- add `BagOfWordsTransformer` to convert a collection of raw documents to matrix representing a bag-of-words structure.
https://github.com/JuliaAI/MLJText.jl/pull/12

cc @ablaom @storopoli

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

release notes:

- Extend compatibility with ScientificTypesBase.jl and ScientificTypes.jl

**Comment by pazzo83** [comment]
@JuliaRegistrator register branch=master

release notes:
- fix bug in fitting `BM25Transformer`

https://github.com/JuliaAI/MLJText.jl/pull/18

cc @ablaom @storopoli

**Comment by pazzo83** [comment]
@JuliaRegistrator register branch=master

release notes:

- BREAKING CHANGE: rename `BagOfWordsTransformer` to `CountTransformer`

https://github.com/JuliaAI/MLJText.jl/pull/20

**Comment by ablaom** [comment]
@pazzo83 Yeah,  no need to keep this  issue open as it is pinned (and otherwise clutters the [JuliaAI Project page](https://github.com/orgs/JuliaAI/projects/1)) .

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master
