### ISSUE TITLE
Migrate text-specific scitype definitions into this package

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/MLJText.jl#7]
Following a [discussion](https://github.com/JuliaAI/ScientificTypes.jl/issues/165) at ScienificTypes, let's move the definition of scientific types out of `ScientificTypesBase`, and move the corresponding implementation of `scitype` out of `ScientificTypes`, into MLJText, prior to release. This is to reduce the dependencies of those general-use packages.

**Comment by pazzo83** [comment]
Perfect!
